# preprocess settings
preprocess:
    resampling: False
    resampling_type: over
    resampling_seed: 71
    os_lim: 10000

# training settings
train:
    mode: reg
    fold_num: 5
    rm_outliers: False
    fold_type: ukf
    single_model: False
    all_features: True
    feature_selection: False
    feature_select_path: 'importances/e005_2019-02-11-00-29-18_3.683_importances.csv'
    metric: 'split_cov'
    feature_topk: 150

# lightGBM parameters
lgbm_params:
    boosting: gbdt
    verbose: -1
    random_state: 71
    objective: regression
    metric: rmse
    learning_rate: 0.01
    num_leaves: 31
    max_depth: -1
    subsample: 0.8
    bagging_freq: 1
    colsample_bytree: 0.8
    min_data_in_leaf: 30
    lambda_l1: 0.1
    min_data_per_group: 1
    cat_smooth: 1
    cat_l2: 0
    max_cat_to_onehot: 10
    #    min_split_gain: 
    #    min_child_weight: 
    #    max_bin: 

# features
features: 
    #    - phase
    - e001_base_max

categorical_features:
    - feature_1
    - feature_2
    - feature_3
    - e002_hist_trans_basic_categorical_merchant_category_id_get_0th_value
    - e002_hist_trans_basic_categorical_merchant_category_id_get_1st_value
    - e002_hist_trans_basic_categorical_merchant_category_id_get_2nd_value
    - e002_hist_trans_basic_categorical_merchant_category_id_get_last_value
    - e002_hist_trans_basic_categorical_state_id_get_0th_value
    - e002_hist_trans_basic_categorical_state_id_get_1st_value
    - e002_hist_trans_basic_categorical_state_id_get_2nd_value
    - e002_hist_trans_basic_categorical_state_id_get_last_value
    - e002_hist_trans_basic_categorical_subsector_id_get_0th_value
    - e002_hist_trans_basic_categorical_subsector_id_get_1st_value
    - e002_hist_trans_basic_categorical_subsector_id_get_2nd_value
    - e002_hist_trans_basic_categorical_subsector_id_get_last_value
    - e002_hist_trans_basic_categorical_city_id_get_0th_value
    - e002_hist_trans_basic_categorical_city_id_get_1st_value
    - e002_hist_trans_basic_categorical_city_id_get_2nd_value
    - e002_hist_trans_basic_categorical_city_id_get_last_value
    - e002_hist_trans_basic_categorical_category_2_get_0th_value
    - e002_hist_trans_basic_categorical_category_2_get_1st_value
    - e002_hist_trans_basic_categorical_category_2_get_2nd_value
    - e002_hist_trans_basic_categorical_category_2_get_last_value
    - e002_hist_trans_basic_categorical_category_3_get_0th_value
    - e002_hist_trans_basic_categorical_category_3_get_1st_value
    - e002_hist_trans_basic_categorical_category_3_get_2nd_value
    - e002_hist_trans_basic_categorical_category_3_get_last_value
    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_last_value
    - e004_new_merc_trans_basic_categorical_state_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_state_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_state_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_state_id_get_last_value
    - e004_new_merc_trans_basic_categorical_subsector_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_subsector_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_subsector_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_subsector_id_get_last_value
    - e004_new_merc_trans_basic_categorical_city_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_city_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_city_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_city_id_get_last_value
    - e004_new_merc_trans_basic_categorical_category_2_get_0th_value
    - e004_new_merc_trans_basic_categorical_category_2_get_1st_value
    - e004_new_merc_trans_basic_categorical_category_2_get_2nd_value
    - e004_new_merc_trans_basic_categorical_category_2_get_0th_value
    - e004_new_merc_trans_basic_categorical_category_3_get_0th_value
    - e004_new_merc_trans_basic_categorical_category_3_get_1st_value
    - e004_new_merc_trans_basic_categorical_category_3_get_2nd_value
    - e004_new_merc_trans_basic_categorical_category_3_get_last_value

invalid_features:
    - card_id
    - target
    - first_active_month
    - outliers
    - e001_hist_trans_basic_numerical_purchase_date_first
    - e001_hist_trans_basic_numerical_purchase_date_last
    - e002_hist_trans_basic_categorical_merchant_id_get_0th_value
    - e002_hist_trans_basic_categorical_merchant_id_get_1st_value
    - e002_hist_trans_basic_categorical_merchant_id_get_2nd_value
    - e002_hist_trans_basic_categorical_merchant_id_get_last_value
    - e003_new_merc_trans_basic_numerical_purchase_date_first
    - e003_new_merc_trans_basic_numerical_purchase_date_last
    - e004_new_merc_trans_basic_categorical_merchant_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_merchant_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_merchant_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_merchant_id_get_last_value
      #    - feature_1
      #    - feature_2
      #    - feature_3
      #    - e002_hist_trans_basic_categorical_merchant_category_id_get_0th_value
      #    - e002_hist_trans_basic_categorical_merchant_category_id_get_1st_value
      #    - e002_hist_trans_basic_categorical_merchant_category_id_get_2nd_value
      #    - e002_hist_trans_basic_categorical_merchant_category_id_get_last_value
      #    - e002_hist_trans_basic_categorical_state_id_get_0th_value
      #    - e002_hist_trans_basic_categorical_state_id_get_1st_value
      #    - e002_hist_trans_basic_categorical_state_id_get_2nd_value
      #    - e002_hist_trans_basic_categorical_state_id_get_last_value
      #    - e002_hist_trans_basic_categorical_subsector_id_get_0th_value
      #    - e002_hist_trans_basic_categorical_subsector_id_get_1st_value
      #    - e002_hist_trans_basic_categorical_subsector_id_get_2nd_value
      #    - e002_hist_trans_basic_categorical_subsector_id_get_last_value
      #    - e002_hist_trans_basic_categorical_city_id_get_0th_value
      #    - e002_hist_trans_basic_categorical_city_id_get_1st_value
      #    - e002_hist_trans_basic_categorical_city_id_get_2nd_value
      #    - e002_hist_trans_basic_categorical_city_id_get_last_value
      #    - e002_hist_trans_basic_categorical_category_2_get_0th_value
      #    - e002_hist_trans_basic_categorical_category_2_get_1st_value
      #    - e002_hist_trans_basic_categorical_category_2_get_2nd_value
      #    - e002_hist_trans_basic_categorical_category_2_get_last_value
      #    - e002_hist_trans_basic_categorical_category_3_get_0th_value
      #    - e002_hist_trans_basic_categorical_category_3_get_1st_value
      #    - e002_hist_trans_basic_categorical_category_3_get_2nd_value
      #    - e002_hist_trans_basic_categorical_category_3_get_last_value
      #    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_0th_value
      #    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_1st_value
      #    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_2nd_value
      #    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_last_value
      #    - e004_new_merc_trans_basic_categorical_state_id_get_0th_value
      #    - e004_new_merc_trans_basic_categorical_state_id_get_1st_value
      #    - e004_new_merc_trans_basic_categorical_state_id_get_2nd_value
      #    - e004_new_merc_trans_basic_categorical_state_id_get_last_value
      #    - e004_new_merc_trans_basic_categorical_subsector_id_get_0th_value
      #    - e004_new_merc_trans_basic_categorical_subsector_id_get_1st_value
      #    - e004_new_merc_trans_basic_categorical_subsector_id_get_2nd_value
      #    - e004_new_merc_trans_basic_categorical_subsector_id_get_last_value
      #    - e004_new_merc_trans_basic_categorical_city_id_get_0th_value
      #    - e004_new_merc_trans_basic_categorical_city_id_get_1st_value
      #    - e004_new_merc_trans_basic_categorical_city_id_get_2nd_value
      #    - e004_new_merc_trans_basic_categorical_city_id_get_last_value
      #    - e004_new_merc_trans_basic_categorical_category_2_get_0th_value
      #    - e004_new_merc_trans_basic_categorical_category_2_get_1st_value
      #    - e004_new_merc_trans_basic_categorical_category_2_get_2nd_value
      #    - e004_new_merc_trans_basic_categorical_category_2_get_0th_value
      #    - e004_new_merc_trans_basic_categorical_category_3_get_0th_value
      #    - e004_new_merc_trans_basic_categorical_category_3_get_1st_value
      #    - e004_new_merc_trans_basic_categorical_category_3_get_2nd_value
      #    - e004_new_merc_trans_basic_categorical_category_3_get_last_value
