# preprocess settings
preprocess:
    resampling: False
    resampling_type: under
    resampling_seed: 71

# training settings
train:
    fold_num: 5
    fold_type: skf
    single_model: False
    all_features: True
    feature_selection: False
    feature_select_path: './importances/e006_2019-01-26-14-05-44_3.688_importances.csv'
    feature_topk: 150

# lightGBM parameters
lgbm_params:
    boosting: gbdt
    verbose: -1
    random_state: 71
    objective: regression
    metric: rmse
    learning_rate: 0.01
    num_leaves: 51
    max_depth: -1
    subsample: 0.8
    bagging_freq: 1
    colsample_bytree: 0.8
    feature_fraction: 0.8
    min_data_in_leaf: 10
    lambda_l1: 0.1
    #    min_split_gain: 
    #    min_child_weight: 
    #    max_bin: 

# features
features: 
    #    - phase
    - e001_base_max

categorical_features:
#    - feature_1
#    - feature_2
#    - feature_3
#    - e002_hist_trans_basic_categorical_merchant_category_id_get_0th_value
#    - e002_hist_trans_basic_categorical_merchant_category_id_get_1st_value
#    - e002_hist_trans_basic_categorical_merchant_category_id_get_2nd_value
#    - e002_hist_trans_basic_categorical_merchant_category_id_get_last_value
#    - e002_hist_trans_basic_categorical_state_id_get_0th_value
#    - e002_hist_trans_basic_categorical_state_id_get_1st_value
#    - e002_hist_trans_basic_categorical_state_id_get_2nd_value
#    - e002_hist_trans_basic_categorical_state_id_get_last_value
#    - e002_hist_trans_basic_categorical_city_id_get_0th_value
#    - e002_hist_trans_basic_categorical_city_id_get_1st_value
#    - e002_hist_trans_basic_categorical_city_id_get_2nd_value
#    - e002_hist_trans_basic_categorical_city_id_get_last_value
#    - e002_hist_trans_basic_categorical_category_2_get_0th_value
#    - e002_hist_trans_basic_categorical_category_2_get_1st_value
#    - e002_hist_trans_basic_categorical_category_2_get_2nd_value
#    - e002_hist_trans_basic_categorical_category_2_get_last_value
#    - e002_hist_trans_basic_categorical_category_3_get_0th_value
#    - e002_hist_trans_basic_categorical_category_3_get_1st_value
#    - e002_hist_trans_basic_categorical_category_3_get_2nd_value
#    - e002_hist_trans_basic_categorical_category_3_get_last_value
#    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_0th_value
#    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_1st_value
#    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_2nd_value
#    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_last_value
#    - e004_new_merc_trans_basic_categorical_state_id_get_0th_value
#    - e004_new_merc_trans_basic_categorical_state_id_get_1st_value
#    - e004_new_merc_trans_basic_categorical_state_id_get_2nd_value
#    - e004_new_merc_trans_basic_categorical_state_id_get_last_value
#    - e004_new_merc_trans_basic_categorical_city_id_get_0th_value
#    - e004_new_merc_trans_basic_categorical_city_id_get_1st_value
#    - e004_new_merc_trans_basic_categorical_city_id_get_2nd_value
#    - e004_new_merc_trans_basic_categorical_city_id_get_last_value
#    - e004_new_merc_trans_basic_categorical_category_2_get_0th_value
#    - e004_new_merc_trans_basic_categorical_category_2_get_1st_value
#    - e004_new_merc_trans_basic_categorical_category_2_get_2nd_value
#    - e004_new_merc_trans_basic_categorical_category_2_get_0th_value
#    - e004_new_merc_trans_basic_categorical_category_3_get_0th_value
#    - e004_new_merc_trans_basic_categorical_category_3_get_1st_value
#    - e004_new_merc_trans_basic_categorical_category_3_get_2nd_value
#    - e004_new_merc_trans_basic_categorical_category_3_get_last_value

invalid_features:
    - card_id
    - target
    - first_active_month
    - outliers
    - e001_hist_trans_basic_numerical_purchase_date_first
    - e001_hist_trans_basic_numerical_purchase_date_last
    - e002_hist_trans_basic_categorical_merchant_id_get_0th_value
    - e002_hist_trans_basic_categorical_merchant_id_get_1st_value
    - e002_hist_trans_basic_categorical_merchant_id_get_2nd_value
    - e002_hist_trans_basic_categorical_merchant_id_get_last_value
    - e003_new_merc_trans_basic_numerical_purchase_date_first
    - e003_new_merc_trans_basic_numerical_purchase_date_last
    - e004_new_merc_trans_basic_categorical_merchant_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_merchant_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_merchant_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_merchant_id_get_last_value
    - feature_1
    - feature_2
    - feature_3
    - e002_hist_trans_basic_categorical_merchant_category_id_get_0th_value
    - e002_hist_trans_basic_categorical_merchant_category_id_get_1st_value
    - e002_hist_trans_basic_categorical_merchant_category_id_get_2nd_value
    - e002_hist_trans_basic_categorical_merchant_category_id_get_last_value
    - e002_hist_trans_basic_categorical_state_id_get_0th_value
    - e002_hist_trans_basic_categorical_state_id_get_1st_value
    - e002_hist_trans_basic_categorical_state_id_get_2nd_value
    - e002_hist_trans_basic_categorical_state_id_get_last_value
    - e002_hist_trans_basic_categorical_city_id_get_0th_value
    - e002_hist_trans_basic_categorical_city_id_get_1st_value
    - e002_hist_trans_basic_categorical_city_id_get_2nd_value
    - e002_hist_trans_basic_categorical_city_id_get_last_value
    - e002_hist_trans_basic_categorical_category_2_get_0th_value
    - e002_hist_trans_basic_categorical_category_2_get_1st_value
    - e002_hist_trans_basic_categorical_category_2_get_2nd_value
    - e002_hist_trans_basic_categorical_category_2_get_last_value
    - e002_hist_trans_basic_categorical_category_3_get_0th_value
    - e002_hist_trans_basic_categorical_category_3_get_1st_value
    - e002_hist_trans_basic_categorical_category_3_get_2nd_value
    - e002_hist_trans_basic_categorical_category_3_get_last_value
    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_merchant_category_id_get_last_value
    - e004_new_merc_trans_basic_categorical_state_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_state_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_state_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_state_id_get_last_value
    - e004_new_merc_trans_basic_categorical_city_id_get_0th_value
    - e004_new_merc_trans_basic_categorical_city_id_get_1st_value
    - e004_new_merc_trans_basic_categorical_city_id_get_2nd_value
    - e004_new_merc_trans_basic_categorical_city_id_get_last_value
    - e004_new_merc_trans_basic_categorical_category_2_get_0th_value
    - e004_new_merc_trans_basic_categorical_category_2_get_1st_value
    - e004_new_merc_trans_basic_categorical_category_2_get_2nd_value
    - e004_new_merc_trans_basic_categorical_category_2_get_0th_value
    - e004_new_merc_trans_basic_categorical_category_3_get_0th_value
    - e004_new_merc_trans_basic_categorical_category_3_get_1st_value
    - e004_new_merc_trans_basic_categorical_category_3_get_2nd_value
    - e004_new_merc_trans_basic_categorical_category_3_get_last_value
